version: "3.8"
services:

  classmanagement:
      build:
        context: ../class_management_app
      expose:
        - "8002"
      environment:
        VIRTUAL_HOST: catesdb.oneagegroup.com
        LETSENCRYPT_HOST: catesdb.oneagegroup.com
        PORT: 8002
      ports:
        - 8002:8002

  oneagegroupcom:
      build:
        context: ../oag_site_web/
      expose:
        - "8001"
      environment:
        VIRTUAL_HOST: oneagegroup.com
        LETSENCRYPT_HOST: oneagegroup.com
        PORT: 8001
      ports:
        - 8001:8001