version: "3.8"
services:
  classmanagement:
      build:
        context: ../class_management_app
      expose:
        - "8002"
      environment:
        VIRTUAL_HOST: catesdb.oneagegroup.com
        LETSENCRYPT_HOST: catesdb.oneagegroup.com
        PORT: 8002
      ports:
        - 8002:8002